import json
from pathlib import Path

import joblib
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import RandomizedSearchCV, StratifiedKFold, train_test_split

ROOT = Path(__file__).resolve().parent
FEATURE_NAMES = [
    "amount_to_sum_insured_ratio", "policy_tenure_years", "reporting_delay_days",
    "past_claim_count", "police_report", "cause_of_loss",
]
INCIDENT_TYPES = [
    "Motor Accident", "Fire", "Theft", "Burglary", "Flood", "Earthquake",
    "Storm", "Medical/Health", "Death", "Property Damage",
    "Third-Party Liability", "Travel/Baggage Loss", "Other",
]
INCIDENT_PROFILES = {
    "Motor Accident": (0.14, 0.52, 0.76, 0.62), "Fire": (0.10, 0.66, 0.82, 0.70),
    "Theft": (0.23, 0.58, 0.78, 0.46), "Burglary": (0.22, 0.55, 0.76, 0.44),
    "Flood": (0.08, 0.62, 0.86, 0.74), "Earthquake": (0.06, 0.68, 0.90, 0.82),
    "Storm": (0.09, 0.60, 0.84, 0.70), "Medical/Health": (0.18, 0.48, 0.72, 0.38),
    "Death": (0.05, 0.72, 0.92, 0.88), "Property Damage": (0.13, 0.56, 0.80, 0.60),
    "Third-Party Liability": (0.16, 0.50, 0.74, 0.48), "Travel/Baggage Loss": (0.29, 0.42, 0.68, 0.28),
    "Other": (0.20, 0.45, 0.70, 0.36),
}


def _sigmoid(value):
    return 1 / (1 + np.exp(-value))


def build_dataset(sample_count=12000, seed=42):
    rng = np.random.default_rng(seed)
    incident_codes = rng.integers(0, len(INCIDENT_TYPES), sample_count)
    profiles = np.array([INCIDENT_PROFILES[INCIDENT_TYPES[index]] for index in incident_codes])
    base_rate, ratio_center, delay_center, report_rate = profiles.T
    amount_ratio = np.clip(rng.beta(2.4, 3.2, sample_count) * 0.92 + (ratio_center - 0.52) * 0.24, 0.08, 0.98)
    tenure = np.clip(rng.gamma(3.2, 2.0, sample_count), 0.2, 25)
    reporting_delay = np.clip(rng.gamma(2.2, 13, sample_count) + (delay_center - 0.7) * 35, 0, 180)
    past_claims = np.clip(rng.poisson(0.85 + base_rate * 3.5, sample_count), 0, 8)
    police_report = (rng.random(sample_count) < report_rate).astype(int)
    risk_signal = (
        (base_rate * 2.5)
        + (amount_ratio > 0.62).astype(float) * 1.5
        + (amount_ratio > 0.82).astype(float) * 1.0
        + (tenure < 1.5).astype(float) * 1.4
        + (reporting_delay > 80).astype(float) * 1.2
        + (past_claims >= 3).astype(float) * 1.35
        + (1 - police_report) * 1.15
    )
    fraud = ((risk_signal + rng.normal(0, 0.12, sample_count)) >= 3.5).astype(int)
    features = np.column_stack((amount_ratio, tenure, reporting_delay, past_claims, police_report, incident_codes))
    return features, fraud


def main():
    features, labels = build_dataset()
    train_features, test_features, train_labels, test_labels = train_test_split(
        features, labels, test_size=0.2, random_state=42, stratify=labels
    )
    search = RandomizedSearchCV(
        RandomForestClassifier(random_state=42, class_weight="balanced", n_jobs=-1),
        {"n_estimators": [240, 320, 420], "max_depth": [8, 12, 16, None], "min_samples_leaf": [1, 2, 4, 7], "max_features": ["sqrt", 0.8, 1.0]},
        n_iter=10, scoring="f1", cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=42),
        random_state=42, n_jobs=-1,
    )
    search.fit(train_features, train_labels)
    model = search.best_estimator_
    predictions = model.predict(test_features)
    report = classification_report(test_labels, predictions, output_dict=True, zero_division=0)
    metrics = {
        "accuracy": round(accuracy_score(test_labels, predictions) * 100, 2),
        "fraud_precision": round(report["1"]["precision"] * 100, 2),
        "fraud_recall": round(report["1"]["recall"] * 100, 2),
        "fraud_f1": round(report["1"]["f1-score"] * 100, 2),
        "confusion_matrix": confusion_matrix(test_labels, predictions).tolist(),
    }
    joblib.dump(model, ROOT / "model.pkl")
    metadata = {
        "validation_accuracy": metrics["accuracy"], "metrics": metrics,
        "feature_order": FEATURE_NAMES,
        "feature_importances": dict(zip(FEATURE_NAMES, [round(float(value), 6) for value in model.feature_importances_])),
        "best_params": search.best_params_,
        "dataset": "Synthetic claims generated by ml/train.py; 12,000 stratified-pattern samples",
    }
    with (ROOT / "model_metadata.json").open("w", encoding="utf-8") as metadata_file:
        json.dump(metadata, metadata_file, indent=2)
    np.savetxt(ROOT / "synthetic_claims.csv", np.column_stack((features, labels)), delimiter=",", header=",".join(FEATURE_NAMES + ["fraud"]), comments="")
    print(json.dumps(metrics, indent=2))
    print(f"Best parameters: {search.best_params_}")


if __name__ == "__main__":
    main()
